services:
  # MongoDB
  postgres:
      container_name: postgres
      image: postgres:latest
      volumes:
        - type: tmpfs
          target: /var/lib/postgresql/data:rw
        - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: workdb123
